export const TITLE = "Intoduction"
export const INTRODUCTION = "In an increasingly complex and regulated environment, a well-crafted constitution is more than just a legal necessity-it's the foundation upon which effective governance is built.For not-for-profit organizations, the constitution is vital in aligning the organization's mission with its operational and legal frameworks, ensuring both compliance and agility in the face of change. This eBook is designed to guide board members, CEOs, governance professionals, and legal advisors through the intricacies of maintaining and updating their constitution. By approaching the constitution as a living document that underpins every aspect of governance, this guide will provide you with the insights and practical tools necessary to ensure your organization's constitution is truly fit for purpose, supporting its long - term success and resilience."
export const INSTRUCTIONS = "This eBook will equip you with practical strategies and expert insights to ensure your organization's constitution is robust, up-to-date, and aligned with best governance practices."

export const CONSTITUTION_TITLE = "The Constitution as a Living Document"
export const CONSTITUTION_SUBTITLE = "Why Your Constitution Needs Regular Review:"
export const CONSTITUTION_DESCRIPTION1 = "A constitution is not a static document meant to sit untouched in a filing cabinet; it is a living, breathing framework that should evolve with your organization.As your organization grows and external regulations change, it's essential to regularly review and update your constitution to ensure it remains relevant and effective. This process helps safeguard the organization's legal standing, aligns governance practices with current operational realities, and supports the achievement of strategic goals.By regularly revisiting the constitution, boards can proactively address potential governance challenges before they become significant issues, ensuring that the organization is always operating in compliance with both its mission and the law."
export const CONSTITUTION_DESCRIPTION2 = "One of the most critical aspects of maintaining a fit-for-purpose constitution is understanding that it must reflect the current practices and procedures of the organization.Regularly reviewing and updating your constitution prevents discrepancies that could lead to legal complications and governance failures."
export const CONSTITUTION_QUOTE = "The Constitution as a Living Document"

